export const cities = [
    { city: "Lagos", country: "Nigeria", currency: "NGN", symbol: "₦" },
    { city: "Abuja", country: "Nigeria", currency: "NGN", symbol: "₦" },
    { city: "London", country: "United Kingdom", currency: "GBP", symbol: "£" },
    { city: "New York", country: "United States", currency: "USD", symbol: "$" },
    { city: "Los Angeles", country: "United States", currency: "USD", symbol: "$" },
    { city: "Paris", country: "France", currency: "EUR", symbol: "€" },
    { city: "Berlin", country: "Germany", currency: "EUR", symbol: "€" },
    { city: "Tokyo", country: "Japan", currency: "JPY", symbol: "¥" },
    { city: "Dubai", country: "UAE", currency: "AED", symbol: "AED" },
    { city: "Accra", country: "Ghana", currency: "GHS", symbol: "₵" },
    { city: "Nairobi", country: "Kenya", currency: "KES", symbol: "KSh" },
    { city: "Johannesburg", country: "South Africa", currency: "ZAR", symbol: "R" },
    { city: "Cape Town", country: "South Africa", currency: "ZAR", symbol: "R" },
    { city: "Dakar", country: "Senegal", currency: "XOF", symbol: "CFA" },
    { city: "Cairo", country: "Egypt", currency: "EGP", symbol: "E£" },
    { city: "Marrakech", country: "Morocco", currency: "MAD", symbol: "MAD" },
    { city: "Toronto", country: "Canada", currency: "CAD", symbol: "C$" },
    { city: "Sydney", country: "Australia", currency: "AUD", symbol: "A$" },
    { city: "Singapore", country: "Singapore", currency: "SGD", symbol: "S$" },
    { city: "Hong Kong", country: "Hong Kong", currency: "HKD", symbol: "HK$" },
    { city: "Mumbai", country: "India", currency: "INR", symbol: "₹" },
    { city: "São Paulo", country: "Brazil", currency: "BRL", symbol: "R$" },
    { city: "Mexico City", country: "Mexico", currency: "MXN", symbol: "Mex$" },
];
