export const cities = [
    // Africa
    { city: "Lagos", country: "Nigeria", currency: "NGN", symbol: "₦" },
    { city: "Abuja", country: "Nigeria", currency: "NGN", symbol: "₦" },
    { city: "Accra", country: "Ghana", currency: "GHS", symbol: "₵" },
    { city: "Nairobi", country: "Kenya", currency: "KES", symbol: "KSh" },
    { city: "Johannesburg", country: "South Africa", currency: "ZAR", symbol: "R" },
    { city: "Cape Town", country: "South Africa", currency: "ZAR", symbol: "R" },
    { city: "Dakar", country: "Senegal", currency: "XOF", symbol: "CFA" },
    { city: "Cairo", country: "Egypt", currency: "EGP", symbol: "E£" },
    { city: "Marrakech", country: "Morocco", currency: "MAD", symbol: "MAD" },
    { city: "Casablanca", country: "Morocco", currency: "MAD", symbol: "MAD" },
    { city: "Addis Ababa", country: "Ethiopia", currency: "ETB", symbol: "Br" },
    { city: "Kigali", country: "Rwanda", currency: "RWF", symbol: "FRw" },

    // Europe - UK
    { city: "London", country: "United Kingdom", currency: "GBP", symbol: "£" },
    { city: "Manchester", country: "United Kingdom", currency: "GBP", symbol: "£" },
    { city: "Birmingham", country: "United Kingdom", currency: "GBP", symbol: "£" },
    { city: "Leeds", country: "United Kingdom", currency: "GBP", symbol: "£" },
    { city: "Glasgow", country: "United Kingdom", currency: "GBP", symbol: "£" },
    { city: "Edinburgh", country: "United Kingdom", currency: "GBP", symbol: "£" },
    { city: "Cardiff", country: "United Kingdom", currency: "GBP", symbol: "£" },
    { city: "Belfast", country: "United Kingdom", currency: "GBP", symbol: "£" },
    { city: "Bristol", country: "United Kingdom", currency: "GBP", symbol: "£" },
    { city: "Liverpool", country: "United Kingdom", currency: "GBP", symbol: "£" },

    // Europe - Continental
    { city: "Paris", country: "France", currency: "EUR", symbol: "€" },
    { city: "Lyon", country: "France", currency: "EUR", symbol: "€" },
    { city: "Marseille", country: "France", currency: "EUR", symbol: "€" },
    { city: "Berlin", country: "Germany", currency: "EUR", symbol: "€" },
    { city: "Munich", country: "Germany", currency: "EUR", symbol: "€" },
    { city: "Frankfurt", country: "Germany", currency: "EUR", symbol: "€" },
    { city: "Madrid", country: "Spain", currency: "EUR", symbol: "€" },
    { city: "Barcelona", country: "Spain", currency: "EUR", symbol: "€" },
    { city: "Rome", country: "Italy", currency: "EUR", symbol: "€" },
    { city: "Milan", country: "Italy", currency: "EUR", symbol: "€" },
    { city: "Amsterdam", country: "Netherlands", currency: "EUR", symbol: "€" },
    { city: "Dublin", country: "Ireland", currency: "EUR", symbol: "€" },
    { city: "Brussels", country: "Belgium", currency: "EUR", symbol: "€" },
    { city: "Zurich", country: "Switzerland", currency: "CHF", symbol: "Fr." },
    { city: "Geneva", country: "Switzerland", currency: "CHF", symbol: "Fr." },
    { city: "Vienna", country: "Austria", currency: "EUR", symbol: "€" },
    { city: "Lisbon", country: "Portugal", currency: "EUR", symbol: "€" },
    { city: "Copenhagen", country: "Denmark", currency: "DKK", symbol: "kr" },
    { city: "Stockholm", country: "Sweden", currency: "SEK", symbol: "kr" },
    { city: "Oslo", country: "Norway", currency: "NOK", symbol: "kr" },
    { city: "Istanbul", country: "Turkey", currency: "TRY", symbol: "₺" },

    // North America - USA/Canada where tipping culture is huge
    { city: "New York", country: "United States", currency: "USD", symbol: "$" },
    { city: "Los Angeles", country: "United States", currency: "USD", symbol: "$" },
    { city: "Chicago", country: "United States", currency: "USD", symbol: "$" },
    { city: "Houston", country: "United States", currency: "USD", symbol: "$" },
    { city: "Miami", country: "United States", currency: "USD", symbol: "$" },
    { city: "San Francisco", country: "United States", currency: "USD", symbol: "$" },
    { city: "Toronto", country: "Canada", currency: "CAD", symbol: "C$" },
    { city: "Vancouver", country: "Canada", currency: "CAD", symbol: "C$" },
    { city: "Montreal", country: "Canada", currency: "CAD", symbol: "C$" },

    // Rest of World
    { city: "Dubai", country: "UAE", currency: "AED", symbol: "AED" },
    { city: "Abu Dhabi", country: "UAE", currency: "AED", symbol: "AED" },
    { city: "Riyadh", country: "Saudi Arabia", currency: "SAR", symbol: "﷼" },
    { city: "Tokyo", country: "Japan", currency: "JPY", symbol: "¥" },
    { city: "Osaka", country: "Japan", currency: "JPY", symbol: "¥" },
    { city: "Seoul", country: "South Korea", currency: "KRW", symbol: "₩" },
    { city: "Singapore", country: "Singapore", currency: "SGD", symbol: "S$" },
    { city: "Hong Kong", country: "Hong Kong", currency: "HKD", symbol: "HK$" },
    { city: "Mumbai", country: "India", currency: "INR", symbol: "₹" },
    { city: "Delhi", country: "India", currency: "INR", symbol: "₹" },
    { city: "Bangkok", country: "Thailand", currency: "THB", symbol: "฿" },
    { city: "Sydney", country: "Australia", currency: "AUD", symbol: "A$" },
    { city: "Melbourne", country: "Australia", currency: "AUD", symbol: "A$" },
    { city: "São Paulo", country: "Brazil", currency: "BRL", symbol: "R$" },
    { city: "Mexico City", country: "Mexico", currency: "MXN", symbol: "Mex$" },
];
